version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shopdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:password@db:5432/shopdb
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: dev-secret
      ACCESS_TOKEN_EXPIRE_MINUTES: "30"
      API_UPLOAD_KEY: dev-upload-key
      CORS_ALLOWED_ORIGINS: http://localhost:5173
      ENV: local
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  worker:
    build: .
    command: celery -A celery_worker.celery_app worker --loglevel=info
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:password@db:5432/shopdb
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: dev-secret
    depends_on:
      - db
      - redis

volumes:
  pgdata:
